---
apiVersion: v1
kind: Secret
metadata:
  name: aks-secret
  namespace: default
type: Opaque
data:
  docker-server: ZGV2b3BzMjAyMS5henVyZWNyLmlv
  docker-username: YzM3NDllNjItYzlhOS00NTBlLWJlNjgtZTJjNjYxMGFmMzQ3
  docker-password: NDE0YWJmOWEtM2NhMy00ODRiLWFhOGUtOTljMjBmMDk2YzY3
  
  