---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql_root_password: cGFzc3dvcmQ=
  mysql_database: b3Blbm1ycw==
  mysql_user: YWRtaW4=
  mysql_user_password: a2lyYW4xMjM=
  